name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/rayst*
            scenes/example.toml
            screenshots/scene.png
            README.md
          generate_release_notes: true
