name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: rayst
          archive: $bin-$tag-$target
          include: scenes/example.toml,README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}