name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: rayst
          target: ${{ matrix.target }}
          changes-file: CHANGELOG.md
          extra-files: |
            README.md
            scenes/
            screenshots/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
